# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 23:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default=django.utils.timezone.now, upload_to='avatar_imgs/'),
            preserve_default=False,
        ),
    ]
