# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-30 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20171220_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, default='30/12/2017', null=True),
        ),
    ]
