# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-04 00:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20180103_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, default='04/01/2018', null=True),
        ),
    ]
