# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-04 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20180104_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, default='04/02/2018', null=True),
        ),
    ]
